import { GoogleGenAI, Type, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Generates meme captions for a given image.
 * @param base64ImageData The base64 encoded image data.
 * @param styleDescription A description of the desired caption style (e.g., "sarcastic and cynical").
 * @returns A promise that resolves to an array of 5 caption strings.
 */
export async function generateCaptions(base64ImageData: string, styleDescription: string = 'funny and witty'): Promise<string[]> {
  const imagePart = {
    inlineData: {
      mimeType: 'image/jpeg',
      data: base64ImageData,
    },
  };

  const textPart = {
    text: `Analyze this image and generate 5 short, ${styleDescription} meme captions. The captions should be distinct from each other. Return the result as a JSON object with a single key 'captions' which is an array of 5 strings.`,
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: { parts: [imagePart, textPart] },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          captions: {
            type: Type.ARRAY,
            items: {
              type: Type.STRING,
            },
            description: 'An array of 5 meme captions.',
          },
        },
        required: ['captions'],
      },
    },
  });

  try {
    const jsonString = response.text.trim();
    const result = JSON.parse(jsonString);
    if (result.captions && Array.isArray(result.captions) && result.captions.length > 0) {
      return result.captions;
    }
  } catch (e) {
    console.error("Failed to parse JSON response from Gemini:", e);
    console.error("Raw response:", response.text);
    throw new Error("The AI returned an unexpected format. Please try again.");
  }
  
  throw new Error("Could not generate captions from the response.");
}

/**
 * Generates a single meme caption for a given image.
 * @param base64ImageData The base64 encoded image data.
 * @param styleDescription A description of the desired caption style.
 * @returns A promise that resolves to a single caption string.
 */
export async function generateSingleCaption(base64ImageData: string, styleDescription: string = 'funny and witty'): Promise<string> {
  const imagePart = {
    inlineData: {
      mimeType: 'image/jpeg',
      data: base64ImageData,
    },
  };

  const textPart = {
    text: `Analyze this image and generate 1 short, ${styleDescription} meme caption. Return the result as a JSON object with a single key 'caption'.`,
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: { parts: [imagePart, textPart] },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          caption: {
            type: Type.STRING,
            description: 'A single meme caption.',
          },
        },
        required: ['caption'],
      },
    },
  });

  try {
    const jsonString = response.text.trim();
    const result = JSON.parse(jsonString);
    if (result.caption) {
      return result.caption;
    }
  } catch (e) {
    console.error("Failed to parse JSON response from Gemini:", e);
    throw new Error("The AI returned an unexpected format.");
  }
  
  throw new Error("Could not generate caption.");
}

/**
 * Edits an image based on a text prompt using Gemini.
 * @param base64ImageData The base64 encoded image data.
 * @param prompt The text prompt describing the desired edit.
 * @returns A promise that resolves to the base64 encoded string of the edited image.
 */
export async function editImageWithGemini(base64ImageData: string, prompt: string): Promise<string> {
  const imagePart = {
    inlineData: {
      data: base64ImageData,
      mimeType: 'image/jpeg',
    },
  };

  const textPart = {
    text: prompt,
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [imagePart, textPart],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the model.");
}